### ISSUE TITLE
Session: Error saving field "title" - reverted to saved value!

### ISSUE THREAD

**Issue by matjazpotocnik** [f-b-g-m/ProcessFileEdit#1]
Hi!

Upon installing the module I got:

`Session: Error saving field "title" - reverted to saved value!`

After submiting the setting, the error is gone.

**Comment by f-b-g-m** [comment]
I just installed it on a site where i never installed it before and got no errors.
Can you tell me what php version you have?

**Comment by matjazpotocnik** [comment]
I'm on 7.0.

I also think there is no need for php4 compatibility as PW itself requires 5.3.8 or newer.

**Comment by f-b-g-m** [comment]
I changed php to version 7, deleted and reinstalled the module, but i got no errors.

Can you give me more info, PW version other installed modules.
Also if you could try on a clean install.

As for the php4 compatibility thing, i got the file tree functions from some site and modified them a little, but forgot to remove that part.

**Comment by matjazpotocnik** [comment]
I think I know what was the problem: if the title is set to required, the this error is thrown, if I remove the required, there is no error. I thing that title is required field on new installation (haven't tried clean install).

**Comment by f-b-g-m** [comment]
Which required are you talking about?

**Comment by matjazpotocnik** [comment]
I'm talking about title system field.

**Comment by f-b-g-m** [comment]
I really don't understand this required title thing.

There are two titles set in this [file](https://github.com/f-b-g-m/ProcessFileEdit/blob/master/ProcessFileEdit.info.php), but there is no required associated with them
1. the plugin title
2. the title of the page where you edit the files

Then there is this [file](https://github.com/f-b-g-m/ProcessFileEdit/blob/master/ProcessFileEdit.config.php) where the fields for the settings are set and some are required, but they all have default values, which are set when the plugin is installed.

Please be more specific.

**Comment by matjazpotocnik** [comment]
I'm sorry for being not specific enough. I've made a "video": https://dl.dropboxusercontent.com/u/3031987/edit.gif

**Comment by f-b-g-m** [comment]
That is a processwire default field and is required by default. 
When the plugin is installed it creates a new page under admin/setup, but for some reason the title can't be saved on your installation.

Disabling the requirement allows you to save a page without a title, so you get no errors, but the cause of the error is still there.

I did a clean PW 3.0.35 and i got no errors, my only guess is there is some conflict with another module.
If suggest you try a clean install.

**Comment by matjazpotocnik** [comment]
Yes, I know all that about title field. I tried this module https://github.com/rolandtoth/ProcessTemplateEditor that also creates a page in admin under setup, but no error there. Tried ProcessExportProfile from adrian, no errors either. I can't see any errors in your code, now this is strange...

**Comment by matjazpotocnik** [comment]
Aha, found it! I had played with hooks on Fieldtype::savePageField in admin.php and forgot about that! Now installed the module without a problem. Sorry for the false alarm.
