### ISSUE TITLE
Undefined variable 

### ISSUE THREAD

**Issue by matjazpotocnik** [f-b-g-m/ProcessFileEdit#2]
When I went to Setup->File editor I get multiple notices:

`Notice: Undefined variable: php_file_tree in C:\inetpub\wwwroot\site\modules\ProcessFileEdit\ProcessFileEdit.module.php on line 149`

and this one:

`Notice: Undefined variable: code in C:\inetpub\wwwroot\site\modules\ProcessFileEdit\ProcessFileEdit.module.php on line 93`

Running on windows, PW 3.0.35, php 7.0, if that info help.

**Comment by f-b-g-m** [comment]
This were fixed.
